FROM node:18-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

COPY frontend/package.json .
COPY frontend/pnpm-lock.yaml .
RUN pnpm install

COPY frontend/ .

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host"]
